{% set name = "wsaccel" %}
{% set version = "0.6.3" %}
{% set sha256 = "fdb27866bb6b6e7a29e45222778ff97938782a0ce92eff07dfb20af8fb9301c4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [python_impl == "pypy"]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - cython
  run:
    - python

test:
  imports:
    - wsaccel
    - wsaccel.xormask
    - wsaccel.utf8validator

about:
  home: https://github.com/methane/wsaccel
  license: Apache 2.0
  license_family: Apache
  # License file is not included in MANIFEST.in in current release so adding copy to recipe.
  # The next release will include the license in the source.
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: WSAccell is WebSocket accelerator for AutobahnPython, and ws4py
  dev_url: https://github.com/methane/wsaccel

extra:
  recipe-maintainers:
    - synapticarbors
