travis:
  secure:
    BINSTAR_TOKEN: PEx8Pun46zEgmtxxyt/slF7XMVXmMXEIFct3ja87Mv67RDz7XWYpxWhdcE1OMwYiZEPtOaFBwhvSXjdn32bQN4OEsdicp6toEfbNlQpJE1kNKmqr2sRj6pGQMks9NO9BaACYdxmUjXGWphZc60C8nnKxr0Qq+haS2OaeyY0qlD063x6EsjDMROOtcFKOoasbjgB3kqiCdZfQm/Yg/gHM7ey3hgAg+tdbURfLifgxJi4aBaaRcvX4hvG6F5ao0PeaUfNNVoG0udjb5JaqnHscD9mhUrzHm1XaOcLmUw5ExD/NkDqxwuX4XGv2MqS9iQO8X7SguJXRWIUsohijS5Ss0dohmZ+9A0UYBMzZgDLjx4SlUN5T6j3tbT/5w7zKlGNWOrhsyYEsPvNeWYWE0OaXvBPvsh3zJ4MBFdkbnnAC7f+Xjb+JKray67xVlzsEGxj8H1QQp8fdMANKCbpvL+/mlPcdMG4fAHiEzQPbJmm3/VasB2M8Vmbwoyn5z7t+5/gOviUH473OV52C6Q/H4bmwfOFPRDngrE0ZlwMR0mGht/ZbOFWhz5JPEVykv+XoOberFLfyLpen1p+YWw4sNeloVktMMmlqKl6rNFXgltsFBD6RoMYB64ZT9F/bTFJW7t9BTqjMJsIU3X2PCCVmLDuAtaRruNGuPvlRAnjnkrnEKho=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
