travis:
  secure:
    BINSTAR_TOKEN: UslKaw5LIWI3VKcyTqErFq3auWj+Pld4YyJfEi3s6KvTwI5IVLFWpYCbpjK4qQ5Kk8ipzZzFJVq38JSBw81mXgcqgszMzobELQf/tnChR81DEKBhj4Jne4JyT3rl5qRmuORkQnXfw33dgN6Ukuqii9XsuIkQxR1f+qza7P4iSfC9xwaQx3a5Bhl25s9DNwF9YzG678Aacr8FghfMCBgzjs3iqS7ICkHB9A2GV+jvMuy09KONL2sLfGvrmz2s0SICxIjkX4Fx9J/yq24bzZHEWUnuWK16U2xnsPLGuDmMKJbYvaUrrgOxwoV8RkmXzC43zVq56/5/KhjozcpnbHHecP9lVI9lm2jD3FLRfaGxCXpGUSxa7vxnGMJjfe42Bkm8/ybY6YJRS/ndWrklu91GCsy2pYaPQRW7/ErnkmmyLMBEikackEO9C7N7/rzbR4YrnbAsLHnuWFNxUWDDU1/EjcW4ZlPFDHviTAHKRk5klijP3pfvo5/Ph4hAAhetgt/AovQhVFfkaDqRpRNiVW5eESSEW7lRMRRsoa0XLtDwmc6486pc0zwtdSwrGCkqhXJBea3BgnEcrB7mcHqENByJszfywxMOZBB5/m+2z6WrR9KqWk1fyWShFuP7F/dg04HrkaH+kxOXjlM1HqiU4MAVSvgWh50Qu/RaiO9JSLTV8Xs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
