travis:
  secure:
    BINSTAR_TOKEN: xRaxDe2t15DWG3SaESRTyeXU6Aoq7ouZ3lsRXkj8eiyZwZhjhKpnsLbXuYDQQwPrHkCVqrxr4ip77JU6x0EUjt6CiO2akU24CkE7/RN3ekaP+VUIvwhZ/rhFcGTdyXbhWloXdjmlgkEsdcmkXb8EXzkcvzXUR7CX+6ScDdwrLGCQHmVeVJxKVV1YS+JvGEArO2Jytj/4cYfV2MTP0lDuq/uZxJE+QFYIDc9kR/+fIVbpKrT7s8VKPoyN9OcofY1sJB1uBLVx6L7tImRtcbrawxg9BS+omCQ0Gbh7qRq3/vAgK5zlsuSKITkp5tFMTJgffzGRw8JjpUJbzzkB9Q1KjyAIcRd4lsnL91SZxFqzLSUoTKtt5x36Se+RYDlwWITZHoAZJlSOFOlkYDOtiltMABDMyJb/QPYUFlIX3FJGCke4AKrTwetgbbqbhL1NUiL5RerA0yvJ+F+ZGwnXfvWbANTy8thoA6KabkHBaGyc4zP6fM8CPKsezSRkvgMTMZesOau4u0chPO/1xvaMjYqYOq70bHpZCFjsx34HjxHwoBoiRTzeA24/psux08PEGBtOIb6rjtfWkwrRThyuBb0yrYzc6RRY3HSX1smknNvWyfFqytHmS/TzEduNIgPhWEMveqKVWInzi/BV3J86Ob7bJCq3HePR6qcbT96n/zSmius=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
