travis:
  secure:
    BINSTAR_TOKEN: J+2C7lvE+noRfhSiKwfmvIOTDF9UFAlg0F6ARIH7WwKqlIKcwVQHAS01t0byWuehQK9pLTxy52Z4FxtAn8/eis9kCbk7Kthshb/Xlz5tj9U2lYAf4WTq5+4yq6Ki6iA3QF1lNAi7U+FOvKNJMOg9CPpQqLgT2k8TxxwXHf0Sud3TxWVindChZRsgRmc6NtJDIhgXZMtvnBWq4QBeYlXqWX25CCpLrMQn5P7QldTqE7/PsgIs7BpnFb25c+FggaN++6MMUyTaWzmqHwdqssY/HBk/pC5Wq+aCl6fkPo4+Yul+g9zLJdCLBpe46Sh39xlHgzBviySEx0I+cXFGaoRhSi8YKMDfTsUbqP/+DqZjp2NJqOl1HVKYHLqmrjYuNsnkdU8Oa2hUoami3FOT7DURyO/zp55CL4TrKDK0Fvn7QQu3iBxDPk4l2aZ+pdlYska561yJn+mJIVc95D8miQi0h1hYL6OoX7fZYupG9cCMVSUESx4wXTEVX5vvLd6OWO5WQ4IJ733ULFrEX5OQnONf6+ahs9oC7oNp6vnNQAGshhHZd4z+s+JREq7HzbcHfwSajyzXI36cSPbHczTk60VcV34kWHZBJUnSaOMlQ9wINVjVQCdRGS7qpjRN9xAvIj8eU9+tnDCQutKEzLjZu2HtUIEUeWQiSzewBkYXdI2O7S0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
